/*
 * MainPanel.java
 *
 * Created on Feb 2, 2010, 1:19:55 PM
 */

package edu.cmu.cs.stage3.alice.authoringtool.dialog;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JToggleButton;
import javax.swing.SpringLayout;

import edu.cmu.cs.stage3.awt.SpringUtilities;
import edu.cmu.cs.stage3.xml.Style;
import edu.cmu.cs.stage3.xml.XMLHelper;

/**
 * 
 * @author Mohammed
 */
@SuppressWarnings("serial")
public class ViStyleFontPanel extends JPanel {

	/** Creates new form MainPanel */
	public ViStyleFontPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	private void initComponents() {

	
		
		
	

		customStyleLbl = new JLabel("Custom Style: ", JLabel.TRAILING);
		customStyleCmb = new JComboBox();
		customStyleCmb.setModel(new DefaultComboBoxModel(XMLHelper
				.getStyleNameList().toArray()));
		customStyleLbl.setLabelFor(customStyleCmb);
		customStyleLbl.setAlignmentX(Component.LEFT_ALIGNMENT);
		customStyleCmb.setAlignmentX(Component.LEFT_ALIGNMENT);
	

		customStyleCmb.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				String styleName = customStyleCmb.getSelectedItem().toString();

				Style style = XMLHelper.getStyleByName(styleName);

				fontSizeCmb.setSelectedItem(style.getFontSize());
				foregroundColor = style.getForgroundColor();

				saveAsBtn.setBackground(foregroundColor);
			}

		});

		fontSizelBL = new javax.swing.JLabel("Font Size: ", JLabel.TRAILING);
		fontSizeCmb = new javax.swing.JComboBox();
		fontSizeCmb.setModel(new javax.swing.DefaultComboBoxModel(XMLHelper
				.getFontSizeList().toArray()));
		fontSizeCmb.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// ColorPickerPanel panel = new ColorPickerPanel();
				int size = Integer.parseInt(fontSizeCmb.getSelectedItem().toString());
				saveAsBtn.setFont(new Font(null, Font.PLAIN, size));

				// System.out.println("color is : "+ newColor);

			}
		});
		fontSizelBL.setLabelFor(fontSizeCmb);
		

		forgroundColorLbl = new javax.swing.JLabel("Forground Color: ", JLabel.TRAILING);
		foreGroundColorBtn = new javax.swing.JToggleButton();
		forgroundColorLbl.setLabelFor(foreGroundColorBtn);
		foreGroundColorBtn.setText("Pick forground Color. . .");
		
		
		backgroundColorLbl = new javax.swing.JLabel("Background Color: ", JLabel.TRAILING);
		backgroundColorBtn = new javax.swing.JToggleButton();
		backgroundColorLbl.setLabelFor(backgroundColorBtn);
		backgroundColorBtn.setText("Pick background Color. . .");
		
		
		foreGroundColorBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jToggleButton1ActionPerformed(evt);

				// ColorPickerPanel panel = new ColorPickerPanel();
				foregroundColor = JColorChooser.showDialog(foreGroundColorBtn, "Choose Color", foregroundColor);
				saveAsBtn.setForeground(foregroundColor);

				// System.out.println("color is : "+ newColor);

			}
		});
		backgroundColorBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				jToggleButton1ActionPerformed(evt);

				// ColorPickerPanel panel = new ColorPickerPanel();
				backgroundColor = JColorChooser.showDialog(backgroundColorBtn, "Choose Color", backgroundColor);
				saveAsBtn.setBackground(backgroundColor);

				// System.out.println("color is : "+ newColor);

			}
		});
		
		defaultCheckBox = new JCheckBox();

		saveAsBtn = new javax.swing.JButton();
		saveAsBtn.setText("Save As a Custom Style. . .");
		saveAsBtn.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				String name = JOptionPane.showInputDialog(this, "mesaage");
				String fontSize = fontSizeCmb.getSelectedItem().toString();

				// System.out.println("color is : "+ color.getRGB());

				XMLHelper.saveStyle(name, fontSize, foregroundColor, backgroundColor);

				customStyleCmb.setModel(new javax.swing.DefaultComboBoxModel(
						XMLHelper.getStyleNameList().toArray()));

				JOptionPane.showMessageDialog(null,
						"style saved successfully. . .");

			}
		});

		cancelBtn = new JButton();
		cancelBtn.setText("Cancel ");
		

		this.setLayout(new SpringLayout());
		this.setAlignmentX(Component.LEFT_ALIGNMENT);
		


		this.add(customStyleLbl);
		this.add(customStyleCmb);
		
		this.add(fontSizelBL);
		this.add(fontSizeCmb);
		
		this.add(forgroundColorLbl);
		this.add(foreGroundColorBtn);
		
		
		this.add(backgroundColorLbl);
		this.add(backgroundColorBtn );
		
		this.add(sampleLabel);
		sampleLabel.setLabelFor(defaultCheckBox);
		/*defaultCheckBox.setMinimumSize(new Dimension(500, 500));
		defaultCheckBox.setMaximumSize(new Dimension(500, 500));
		defaultCheckBox.setPreferredSize(new Dimension(500, 500));*/
		//defaultCheckBox.
		this.add(defaultCheckBox);
		
		
		this.add(cancelBtn);
		this.add(saveAsBtn);
		
		
		
		
		
		SpringUtilities.makeCompactGrid(this,
                6 , 2, //rows, cols
                0, 0,        //initX, initY
                6, 6);       //xPad, yPad
		this.setVisible(true);

	}// </editor-fold>

	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:

	}

	// Variables declaration - do not modify
	private JButton cancelBtn;
	private JButton saveAsBtn;
	private JComboBox customStyleCmb;
	private JComboBox fontSizeCmb;
    private JCheckBox defaultCheckBox;
	private JLabel customStyleLbl;
	private JLabel fontSizelBL;

	private JLabel forgroundColorLbl;
	private JLabel backgroundColorLbl;
	private JToggleButton foreGroundColorBtn;
	private JToggleButton backgroundColorBtn;
	JLabel sampleLabel = new JLabel("set as a default");

	private static Color foregroundColor;
	private static Color backgroundColor;
	// End of variables declaration

}
